version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    reviewers:
      - "vano44"
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "npm"
      prefix-development: "npm-dev"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    reviewers:
      - "vano44"
    labels:
      - "dependencies"
      - "docker"
